### ISSUE TITLE
about the issue thing on scratch

### ISSUE THREAD

**Issue by imdevarsh** [JaydenDev/osinfo#1]
Yeah, just wondering if you use npm or yarn or some other manager? Or if you didn't use any, in which case you should use one, then you can develop and test on localhost.

**Comment by jdev082** [comment]
there is a package.json where packages are installed during deployment

**Comment by jdev082** [comment]
i dont NEED notifications its really an experiment
what I needa know is how I should show the WinInfo information. A table? A dynamic Table? Somethin else?

**Comment by imdevarsh** [comment]
Oh

**Comment by imdevarsh** [comment]
Then maybe you should show it in a table then, a dynamic table like one with JS?

**Comment by jdev082** [comment]
i dont want just any table, i want a fancy one. I see some svelte UI frameworks, in case I want a material or some other theme.

**Comment by jdev082** [comment]
might not be a right choice, I don't want this to be overly eye-candy

**Comment by imdevarsh** [comment]
I may have to go soon.
So you want a table with CSS? Then you should use that, default table looks kind of bad.

**Comment by jdev082** [comment]
Well, CSS might not exactly be enough. Not sure if I want a table even, here is a quick mockup of what kind of UI I've been thinking:

![image](https://user-images.githubusercontent.com/92550746/138202797-42ce68e1-be93-489c-a621-310086d90586.png)

**Comment by jdev082** [comment]
If I did this the usual vanilla HTML-CSS-JS  way, I would have hundreds of HTML files for popups alone. And a annoying amount of javascript. Popups? In the same tab?

**Comment by jdev082** [comment]
accidentily closed

**Comment by imdevarsh** [comment]
Ok. So basically each version has its own little card?

**Comment by jdev082** [comment]
Yeah, but a dynamic card :p

**Comment by imdevarsh** [comment]
If so then you could make an object with information and use Svelte to loop over it.

**Comment by imdevarsh** [comment]
Like this (just a test)
[{"name": "Windows 11", "thing": "another"}, {"name": "Windows 10", "thing": "another"}]

**Comment by jdev082** [comment]
define 'loop over it'
'object'?

**Comment by imdevarsh** [comment]
Well, you know the things in JS with curly braces like {}

**Comment by jdev082** [comment]
```
function makePopup {
  *popup code placeholder*
}

<button onclick="makePopup()">Button</button>
```

**Comment by imdevarsh** [comment]
In Svelte you can use the #each to loop over it. https://svelte.dev/tutorial/each-blocks

**Comment by imdevarsh** [comment]
Sorry if you feel like I am forcing you

**Comment by jdev082** [comment]
> 
> 
> In Svelte you can use the #each to loop over it. https://svelte.dev/tutorial/each-blocks

looks like that code made the entire website white

**Comment by imdevarsh** [comment]
> > In Svelte you can use the #each to loop over it. https://svelte.dev/tutorial/each-blocks
> 
> looks like that code made the entire website white

No you're supposed to learn how to add in the {#each}
Edit: The **entire** website including editor? That might not be a working website on your browser then.

**Comment by jdev082** [comment]
> 
> 
> > > In Svelte you can use the #each to loop over it. https://svelte.dev/tutorial/each-blocks
> > 
> > 
> > looks like that code made the entire website white
> 
> No you're supposed to learn how to add in the {#each}

I configured the variables and all, but the white screen is still tehre.

**Comment by jdev082** [comment]
i have to go

**Comment by imdevarsh** [comment]
Oh well, bye. Same I am going soon

**Comment by imdevarsh** [comment]
Hi

**Comment by jdev082** [comment]
can you also make the background black and the cards white while im gone

**Comment by imdevarsh** [comment]
sure!

**Comment by imdevarsh** [comment]
#3 I've opened up a pull request for your thing
