### ISSUE TITLE
Design Changes 19.2.2022

### ISSUE THREAD

**Issue by jdev082** [JaydenDev/osinfo#15]
These are very necessary:

1. Make search bar consistent with the rest of the interface.
2. Make search bar take entire page width

**Comment by jdev082** [comment]
When making these changes, commit to the beta branch for in-depth testing.

**Comment by jdev082** [comment]
These changes are being postponed, we are now focusing on the changes and bug fixes that kccuber is writing and committing.

**Comment by jdev082** [comment]
unlocked

**Comment by imdevarsh** [comment]
Sovled by #19 I think
