### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kccuber-scratch** [JaydenDev/osinfo#20]
Umm... what license is this? MIT?

**Comment by jdev082** [comment]
A license hasn't really been added yet

**Comment by imdevarsh** [comment]
add the license now.. it will be better.. do it..

**Comment by jdev082** [comment]
> add the license now.. it will be better.. do it..

maybe later

**Comment by imdevarsh** [comment]
> maybe later

Add a license!! It will protect our work!!

**Comment by jdev082** [comment]
> > maybe later
> 
> Add a license!! It will protect our work!!

fine...
