### ISSUE TITLE
Web Bundle releases?

### ISSUE THREAD

**Issue by hello-smile6** [JaydenDev/osinfo#23]
If you provided web bundles for each release, maybe more people would use this.

**Comment by jdev082** [comment]
Please elaborate on what a "Web Bundle" is as no resource explains it online. But after that the answer will still be no.

**Comment by hello-smile6** [comment]
> Please elaborate on what a "Web Bundle" is as no resource explains it online. But after that the answer will still be no.

https://web.dev/web-bundles

**Comment by jdev082** [comment]
> > Please elaborate on what a "Web Bundle" is as no resource explains it online. But after that the answer will still be no.
> 
> https://web.dev/web-bundles

If it can't be automatic through github actions, it isn't happening

**Comment by hello-smile6** [comment]
> > > Please elaborate on what a "Web Bundle" is as no resource explains it online. But after that the answer will still be no.
> > 
> > 
> > https://web.dev/web-bundles
> 
> If it can't be automatic through github actions, it isn't happening

How about hourly deployments with no interaction?
https://github.com/hello-smile6/turbowarp-web-bundle-builder

**Comment by jdev082** [comment]
> > > > Please elaborate on what a "Web Bundle" is as no resource explains it online. But after that the answer will still be no.
> > > 
> > > 
> > > https://web.dev/web-bundles
> > 
> > 
> > If it can't be automatic through github actions, it isn't happening
> 
> How about hourly deployments with no interaction? https://github.com/hello-smile6/turbowarp-web-bundle-builder

this isn't at all a scratch project, this is a web application. Also, this is useless. Stop making useless issue reports or you will be denied ability to do so. Also stop making issue reports just to advertise your own products.

**Comment by hello-smile6** [comment]
> > > > > Please elaborate on what a "Web Bundle" is as no resource explains it online. But after that the answer will still be no.
> > > > 
> > > > 
> > > > https://web.dev/web-bundles
> > > 
> > > 
> > > If it can't be automatic through github actions, it isn't happening
> > 
> > 
> > How about hourly deployments with no interaction? https://github.com/hello-smile6/turbowarp-web-bundle-builder
> 
> this isn't at all a scratch project, this is a web application. Also, this is useless. Stop making useless issue reports or you will be denied ability to do so. Also stop making issue reports just to advertise your own products.

That's just an example. I was showing you that it was possible. Fine, I'll add your repository to the build for that one.

**Comment by jdev082** [comment]
> > > > > > Please elaborate on what a "Web Bundle" is as no resource explains it online. But after that the answer will still be no.
> > > > > 
> > > > > 
> > > > > https://web.dev/web-bundles
> > > > 
> > > > 
> > > > If it can't be automatic through github actions, it isn't happening
> > > 
> > > 
> > > How about hourly deployments with no interaction? https://github.com/hello-smile6/turbowarp-web-bundle-builder
> > 
> > 
> > this isn't at all a scratch project, this is a web application. Also, this is useless. Stop making useless issue reports or you will be denied ability to do so. Also stop making issue reports just to advertise your own products.
> 
> That's just an example. I was showing you that it was possible. Fine, I'll add your repository to the build for that one.

Have you noticed I said "no" already? Be quiet please
