### ISSUE TITLE
Dark Mode Broken

### ISSUE THREAD

**Issue by jdev082** [JaydenDev/osinfo#7]
i broke dark mode :/

**Comment by imdevarsh** [comment]
well let me see.. could we revert to https://github.com/JaydenDev/wininfosvelte/commit/5973d1b72b2f34a8743793839c46ed3118d2bfc5

**Comment by jdev082** [comment]
there are still broken aspects before that commit i believe

**Comment by imdevarsh** [comment]
ok, like what?

**Comment by imdevarsh** [comment]
i know that there is a little border between the theme background and the page, i'm trying to think of a solution

**Comment by jdev082** [comment]
the solution'd prolly be height: 100% width: 100%

**Comment by imdevarsh** [comment]
> the solution'd prolly be height: 100% width: 100%

min-height and min-width would allow for expansion of the page too

**Comment by jdev082** [comment]
There isn't even a light mode anymore so...
